upstream kai-gateway-upstream {
  server 127.0.0.1:9000;
  keepalive 64;
}

upstream kai-mcp-upstream {
  server 127.0.0.1:9200;
  keepalive 64;
}

server {
  listen 80;
  server_tokens off;

  root /var/www/kai;

  location ^~ / {
    return 404;
  }

  location /chat {
    alias /var/www/kai/chat;
    index index.html;
    try_files $uri $uri/ =404;
  }

  location /api/v1/ {

	  #rewrite ^/api/v1/(.*)$ /$1 break;

    if ($request_method = 'OPTIONS') {
      add_header Access-Control-Allow-Origin $http_origin;
      add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE";
      add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,X-PINGARUNER,origin,accept";
      add_header Access-Control-Expose-Headers "Content-Length,Content-Range";
      add_header Access-Control-Allow-Credentials "true";
      add_header Access-Control-Max-Age 1728000;
      add_header 'Content-Type' 'text/plain; charset=utf-8';
      add_header 'Content-Length' 0;
      return 204;
    }

    add_header Access-Control-Allow-Origin $http_origin always;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
    add_header Access-Control-Allow-Headers "User-Agent,Cache-Control,Content-Type,Authorization,origin,accept" always;

    send_timeout 601s;
    proxy_read_timeout 600s;

    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # --------- IMPORTANT: pass through gateway debug header to client ----------
    proxy_pass_header X-Gateway-Backend;

    proxy_pass http://kai-gateway-upstream/;
  }
}


server {
  listen 8200;
  server_tokens off;

  root /var/www/kai;

  location ^~ / {
    return 404;
  }

  location /api/v1/ {

	  #rewrite ^/api/v1/(.*)$ /$1 break;

    if ($request_method = 'OPTIONS') {
      add_header Access-Control-Allow-Origin $http_origin;
      add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE";
      add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,X-PINGARUNER,origin,accept";
      add_header Access-Control-Expose-Headers "Content-Length,Content-Range";
      add_header Access-Control-Allow-Credentials "true";
      add_header Access-Control-Max-Age 1728000;
      add_header 'Content-Type' 'text/plain; charset=utf-8';
      add_header 'Content-Length' 0;
      return 204;
    }

    add_header Access-Control-Allow-Origin $http_origin always;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
    add_header Access-Control-Allow-Headers "User-Agent,Cache-Control,Content-Type,Authorization,origin,accept" always;

    send_timeout 601s;
    proxy_read_timeout 600s;

    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;


    proxy_pass http://kai-mcp-upstream/;
  }
}

server {
  listen 8180;

  location /kai/node/ {
    proxy_pass http://localhost:9100/;
  }

  location /kai/model/ {
    proxy_pass http://kai-gateway-upstream/;
    proxy_set_header Connection "";
    proxy_http_version 1.1;
    proxy_pass_header X-Gateway-Backend;
  }
}
